### ISSUE TITLE
Taking long for Bayesian Echo

### ISSUE THREAD

**Issue by arvindilamaran** [Computational-Content-Analysis-2018/Content-Analysis#10]
I was able to debug the Bayesian Echo Chamber routine only late in the evening. The run is still in progress. Should I update the results after 12 am? or will there be deductions for that too?

**Comment by linzhuoliSOC** [comment]
There will not be deductions. Although you may need to send a copy the latest notebook via email to TAs.


On Feb 28, 2018, at 11:05 PM, Arvind V. Ilamaran <notifications@github.com<mailto:notifications@github.com>> wrote:


I was able to debug the Bayesian Echo Chamber routine only late in the evening. The run is still in progress. Should I update the results after 12 pm? or will there be deductions for that too?
