### ISSUE TITLE
Problems with pushing to git

### ISSUE THREAD

**Issue by xiangyum** [Computational-Content-Analysis-2018/Content-Analysis#4]
I'm having issues pushing to git. I've tried to do so in terminal and in a git client (GitKraken), and in both instances it takes a long time (>1.5 hr) and eventually fails. What seems to be happening is that Git ends up pushing a ridiculous amount of objects (>40,000) that ends up being over 1.1 gig in size.

I don't understand what's happening. My data is only 4.5mb, and the total size of the files I added can't be more than 10mb. Some help would be greatly appreciated. I've attached the error that I get.
<img width="1160" alt="screen shot 2018-01-25 at 9 17 39 am" src="https://user-images.githubusercontent.com/32276953/35395704-bb54500e-01b0-11e8-8a0f-5e2fe8d5054e.png">

**Comment by reidmcy** [comment]
Hi Xiangyu,

It looks like some of the nltk files are too large for GitHub. Please try running these two commands:
```
git filter-branch -f --index-filter "git rm -rf --cached --ignore-unmatch data/corpora" -- --all
git filter-branch -f --index-filter "git rm -rf --cached --ignore-unmatch data/models" -- --all 
```
They should remove the large files from your history. The pull from the base `git pull base master` as that will prevent it from happening agin.

Reid

**Comment by xiangyum** [comment]
I'm running into more trouble with merge conflicts etc. I think it might be the residuals from my (inept) attempts at trying to fix things. Is there any way I can nuke the entire thing and start over? This is becoming unbelievably frustrating.

**Comment by reidmcy** [comment]
Yes, nuking after a merge issues is common solution. You need to clone the repo from GitHub to new location, so maybe rename your current copy then run this command:
```
git clone https://github.com/xiangyum/content-analysis-2018.git
```
Then you should add the the base repo and pull from it:
```
cd content-analysis-2018
git remote add base https://github.com/Computational-Content-Analysis-2018/Content-Analysis.git
git pull base master
```

Then copy all your files from the old repo to the new one and push.

[![](https://imgs.xkcd.com/comics/git_2x.png)](https://xkcd.com/1597)

**Comment by xiangyum** [comment]
Thank you so much! I finally got it to work. You're a life saver. I didn't know an inanimate piece of code would provoke so much angst and fury in me, but git managed for the better part of the past 12 hours. I'll keep your advice in mind for the next time I run into trouble with it.
