### ISSUE TITLE
Importing Proquest data into python?

### ISSUE THREAD

**Issue by xiangyum** [Computational-Content-Analysis-2018/Content-Analysis#5]
I'm trying to work with newspaper data that I got from Proquest for my final project. They're in .txt formats. I'm unsure what the best approach for importing them and converting them into a dictionary/dataframe is. They're not delimited in a straightforward way. I've copy-pasted a sample of the .txt file below (I've replaced text with square brackets in the interest of saving space]. I'd really appreciate it if you could describe in pseudo code one possible approach, or point me to a resource that's relevant to this. Thank you.

Sample:

____________________________________________________________

[Title of article 1]

Author: Emilyn Yap And

Publication info: The Business Times ; Singapore [Singapore]24 May 2012.

https://search.proquest.com/docview/1015595477?accountid=14657

Abstract: [stuff]

Links: [stuff]

Full text: [TEXT]

Publication title: The Business Times; Singapore

Publication year: 2012

Publication date: May 24, 2012

Section: Top Stories

Publisher: The Financial Times Limited

Place of publication: Singapore

Country of publication: United Kingdom, Singapore

Publication subject: Business And Economics

Source type: Newspapers

Language of publication: English

Document type: News

ProQuest document ID: 1015595477

Document URL: https://search.proquest.com/docview/1015595477?accountid=14657

Copyright: (Copyright 2012 Singapore Press Holdings)

Last updated: 2012-05-24

Database: Global Newsstream

____________________________________________________________

[Article 2 ...]

**Comment by reidmcy** [comment]
You closed this question, so I'm not sure if you've figured it out.

ProQuest is actually a really terrible to read format to read, which is why I wrote a parse for it a couple years ago. It's part of a larger package called [`metaknowledge`](http://networkslab.org/metaknowledge), so if you want to convert ProQuest text files to dataframes you do something like:
```
import metaknowledge
RC = metaknowledge.RecordCollection('path to ProQuest file or directory of files')
df = pandas.DataFrame(RC.makeDict())
```

Hope this helps,
Reid

**Comment by xiangyum** [comment]
Ah gotcha. It took me some time, but I cobbled together a function that to do that, that's why I closed the issue. But thanks anyway! It would have been super useful.
