### ISSUE TITLE
Error: NLTK can't find java

### ISSUE THREAD

**Issue by t-a-trahan** [Computational-Content-Analysis-2018/Content-Analysis#6]
Edit: Obviously should have led with this - I do have Java 1.8 installed. 

I'm having trouble getting the stanford-NLP to work for hw7. 

When I run the code:

`pos_sents = stanford.postTagger.tag_sents(tokenized_text)`

I get the error message: 

`NLTK was unable to find the java file!
Use software specific configuration paramaters or set the JAVAHOME environment variable.`

I've tried setting the JAVA_HOME variable with the following code, but I still get the same error message.

`JAVA_HOME = 'C:/Program Files/Java/jdk1.8.0_161/bin/java`

**Link to full traceback:**

https://gist.github.com/t-a-trahan/03f15877daa3b67e6834315fef257d7d

Thanks in advance for all help!!!

**Comment by reidmcy** [comment]
I think the easist thing to do is avoid the JAVAPATH entirely. You can tell nltk where java is with something like this:

```
import nltk
nltk.internals.config_java("path to java.exe") #e.g. C:/Program Files/Java/jdk1.8.0_161/bin/java.exe
```
You might need to do this before importing `lucem_illud` some make this the first cell, and make sure to restart the kernel before running it.

[source] [https://stackoverflow.com/a/10844136/4955164](https://stackoverflow.com/a/10844136/4955164)

**Comment by reidmcy** [comment]
Another student reported this working and I've had success with something like it on a test machine. 

```
import os
os.environ['JAVAHOME'] =  "C:/Program Files/Java/jdk1.8.0_161/bin/java.exe"
```

If nothing works please use the server

**Comment by t-a-trahan** [comment]
For whatever reason, the `nltk.internals.config_java` solution did not work.

But, shortly before the most recent post I actually was able to get my script working using that exact solution - i.e., `os.environ['JAVAHOME']` ...

Thanks for the suggests! 

Here's the source where I found the solution that worked:
https://stackoverflow.com/questions/7404720/nltk-fails-to-find-the-java-executable

**Comment by joelmathewphilip** [comment]
> Another student reported this working and I've had success with something like it on a test machine.
> 
> ```
> import os
> os.environ['JAVAHOME'] =  "C:/Program Files/Java/jdk1.8.0_161/bin/java.exe"
> ```
> 
> If nothing works please use the server

This one actually worked in my windows machine when i mentioned it as 
import os
os.environ['JAVAHOME'] =  "C:\\Program Files\\Java\\jdk-15.0.1\\bin\\java.exe"

I suppose you can copy paste your java file link and then use double slash everywhere in the link...

**Comment by prasadovhal** [comment]
Putting double slash in path did work, Thanks
