### ISSUE TITLE
Hw3 ungraded

### ISSUE THREAD

**Issue by xiangyum** [Computational-Content-Analysis-2018/Content-Analysis#7]
Hey Reid/Linzhuo,

My assignment 3 doesn't appear to have been graded (at least that's what it looks like on canvas). Just thought I'd let you know.

**Comment by linzhuoliSOC** [comment]
will grade it soon.


On Feb 20, 2018, at 7:48 PM, Xiangyu Ma <notifications@github.com<mailto:notifications@github.com>> wrote:


Hey Reid/Linzhuo,

My assignment 3 doesn't appear to have been graded (at least that's what it looks like on canvas). Just thought I'd let you know.

**Comment by xiangyum** [comment]
Thank you!
