### ISSUE TITLE
Trouble with lucem_illud.bec_run

### ISSUE THREAD

**Issue by sushmitavgopalan16** [Computational-Content-Analysis-2018/Content-Analysis#9]
Hi TAs!

I'm having an issue with locating the results of running a bayesian echo chamber - the function finishes running in ~ 2 seconds and no results folder is generated - what could I be doing wrong?
Have pushed my latest code!

**Comment by linzhuoliSOC** [comment]
Can you see any results in the shell?  Are you using RCC or your own machine?
On Feb 28, 2018, at 9:53 PM, Sush <notifications@github.com<mailto:notifications@github.com>> wrote:


Hi TAs!

I'm having an issue with locating the results of running a bayesian echo chamber - the function finishes running in ~ 2 seconds and no results folder is generated - what could I be doing wrong?
Have pushed my latest code!

**Comment by sushmitavgopalan16** [comment]
I'm running it on my own machine! I ran the command on my jupyter notebook and I'm not sure where to look next - any help would be appreciated! :)

**Comment by linzhuoliSOC** [comment]
If you switch to your “shell/terminal”, can you see any realtime results?
On Feb 28, 2018, at 10:00 PM, Sush <notifications@github.com<mailto:notifications@github.com>> wrote:


I'm running it on my own machine! I ran the command on my jupyter notebook and I'm not sure where to look next - any help would be appreciated! :)

**Comment by xiangyum** [comment]
I had similar issues with this; I checked terminal and found that the function was interrupted because of errors (in my case, some of the start and end times were the same) in the xml file. Maybe you're running into similar troubles.

**Comment by sushmitavgopalan16** [comment]
Oh! I just noticed this error - "FileNotFoundError: [Errno 2] No such file or directory: './stopwords/english.stop'" Where should I put this file?

**Comment by sushmitavgopalan16** [comment]
I do have the file in data/corpora/stopwords/

**Comment by xiangyum** [comment]
Make a new folder named stopwords in your working folder (i.e. the HW8 folder) and put the file there. That should work.

**Comment by sushmitavgopalan16** [comment]
That worked - thank you so much!
